AgileTech_Web/Models/APIRequest.cs
using static AgileTech_Utility.DS;

namespace AgileTech_Web.Models
{
    public class APIRequest
    {
        public APIType APIType { get; set; } = APIType.GET;

        public string Url { get; set; }

        public object Data { get; set; }

        public string IsHubspot { get; set; } = null;
    }
}

AgileTech_Web/Models/APIResponse.cs
using System.Net;

namespace AgileTech_Web.Models
{
    public class APIResponse
    {
        public HttpStatusCode StatusCode { get; set; }

        public bool IsSuccess { get; set; } = true;
        
        public List<string> Errors { get; set; }

        public object Result { get; set; }
    }
}

AgileTech_Web/Models/Dto/ClientCreateDto.cs
using System.ComponentModel.DataAnnotations;

namespace AgileTech_Web.Models.Dto
{
    public class ClientCreateDto
    {
        [Required]
        [MaxLength(30)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

    }
}

AgileTech_Web/Models/Dto/ClientCreateHubspotDto.cs
using System.ComponentModel.DataAnnotations;

namespace AgileTech_Web.Models.Dto
{
    public class ClientCreateHubspotDto
    {
        [Required]
        public object properties { get; set; }


    }
}

AgileTech_Web/Models/Dto/ClientDto.cs
using System.ComponentModel.DataAnnotations;

namespace AgileTech_Web.Models.Dto
{
    public class ClientDto
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(30)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

    }  
}

AgileTech_Web/Models/Dto/ClientHubspotDto.cs
using System.ComponentModel.DataAnnotations;

namespace AgileTech_Web.Models.Dto
{
    public class ClientHubspotDto
    {

        [Required]
        public object properties { get; set; }


    }  
}

AgileTech_Web/Models/Dto/ClientUpdateDto.cs
using System.ComponentModel.DataAnnotations;

namespace AgileTech_Web.Models.Dto
{
    public class ClientUpdateDto
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [MaxLength(30)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

    }
}

AgileTech_Web/Models/ErrorViewModel.cs
namespace AgileTech_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgileTech_Web/Controllers/ClientController.cs
using AgileTech_Web.Models;
using AgileTech_Web.Models.Dto;
using AgileTech_Web.Services.IServices;
using AutoMapper;
using AutoMapper.Internal;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.CodeModifier.CodeChange;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Newtonsoft.Json;
using NuGet.Protocol.Plugins;
using System.Reflection;


namespace AgileTech_Web.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;
        private readonly IMapper _mapper;

        public ClientController(IClientService clientService, IMapper mapper)
        {
            _clientService = clientService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexClient()
        {

            List<ClientDto> clientList = new();

            var response = await _clientService.GetAll<APIResponse>();

            if (response != null && response.IsSuccess) 
            {
                clientList = JsonConvert.DeserializeObject<List<ClientDto>>(Convert.ToString(response.Result));
            }
            return View(clientList);

        }

        public async Task<IActionResult> HubspotClient()
        {

            List<ClientHubspotDto> clientList = new();

            var responseHubspot = await _clientService.GetAllHubspot<APIResponse>();

            Console.WriteLine(string.Join("----sebas, ", responseHubspot.Result));

            //Console.WriteLine("pajaro" + responseHubspot );

 
            if (responseHubspot != null)
            {
              clientList = JsonConvert.DeserializeObject<List<ClientHubspotDto>>(Convert.ToString(responseHubspot.Result));
            }
            return NoContent();
            //return View(clientList);
        }

        public async Task<IActionResult> SendTo(int id) 
        {

            ClientDto clientDto = new();
            var responseApi = await _clientService.Get<APIResponse>(id);
            if (responseApi != null && responseApi.IsSuccess)
            {
                clientDto = JsonConvert.DeserializeObject<ClientDto>(Convert.ToString(responseApi.Result));

                var data = new ClientCreateHubspotDto
                {
                    properties = new
                    {
                        email = clientDto.Email,
                        firstname = clientDto.Name,
                        idapi = clientDto.Id
                    }
                };

                var response = await _clientService.CreateHubspot<APIResponse>(data);
                if (response != null && response.IsSuccess)
                {
                   return RedirectToAction(nameof(HubspotClient));
                }

            }
            return NotFound();
        }
    }
}

AgileTech_Web/Controllers/HomeController.cs
using AgileTech_Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AgileTech_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgileTech_Web/Views/Client/IndexClient.cshtml
@model IEnumerable<AgileTech_Web.Models.Dto.ClientDto>

@{
    ViewData["Title"] = "IndexClient";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div calss="container p-4 border">
    <div class="row pg-2">
        <h1 class="text-primary">Client List</h1>
    </div>
    <div class="col text-end pt-1">
        <a asp-controller="Client" asp-action="SedTo" class="btn btn-outline-primary"><i class="bi bi-send"></i>Send All to HubSpot</a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Email</td>
                    <td> <a asp-controller="Client" asp-action="SendTo" asp-route-id="@item.Id" class="btn btn-outline-primary"><i class="bi bi-send"></i>Send to HubSpot</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

AgileTech_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AgileTech_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgileTech_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgileTech_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AgileTech_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="IndexClient">API Clients</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="HubspotClient">HubsPot Clients</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AgileTech_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>